### ISSUE TITLE
GD crashes when invoking IconSave (Geode)

### ISSUE THREAD

**Issue by aviumcaravan** [not-nef/IconSave#4]
## what should happen?

a profile loading or the saved icons folder opening.

## what happens?

an invalid C runtime parameter being passed (``0xc0000417``/``STATUS_INVALID_CRUNTIME_PARAMETER``).

## steps to reproduce

1. open GD with IconSave loaded
2. open any profile, including your own OR open the folder in your icon selection menu.

## log file

[2023-11-18_11-06-56.log](https://github.com/not-nef/IconSave/files/13399970/2023-11-18_11-06-56.log)

## temporary solution

disabling the mod.

## hardware

* CPU: AMD Ryzen 5 2600
* GPU: Sapphire NITRO+ RX 580 4 GB

## software

* OS: Arch Linux w/ Proton Experimental through Steam
* Geometry Dash: v2.113
* Geode: v1.3.6

**Comment by aviumcaravan** [comment]
P.S. note: this started happening **today**, no Proton or Geode updates.

**Comment by not-nef** [comment]
does that mean it worked before?

**Comment by aviumcaravan** [comment]
yes, it broke rather suddenly today, with the log being identical every time i ran the game, save for the timestamp. the backtrace is identical. not even sure what happened, but we went from "yeah it works 👍🏻" to "0xc0000417" over the span of roughly 13 hours.

**Comment by aviumcaravan** [comment]
(i misclicked, my bad, but yeah, it came up suddenly.)

**Comment by not-nef** [comment]
sounds like a corrupted save or a mod compatibility issue. try to delete your iconkitmanager.dat and disable any mods that you installed in that timeframe. if the problem persists, the mod will be rewritten in 2.2 anyway since it will 100% break because it has lots of hardcoded ids and patches that i haven't looked into while porting.

**Comment by aviumcaravan** [comment]
correct, seems like the savefile got corrupted. after moving it to a backup dir the game and the mod both work fine. is there a chance that i managed to cause an overflow?

**Comment by aviumcaravan** [comment]
update: fixed it by reloading the mod, it seems i did have an overflow but it got removed on a reload.
